// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectDL;

namespace ProjectDL.Migrations
{
    [DbContext(typeof(ProjectDBContext))]
    partial class ProjectDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ProjectModels.Pattern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("PatternData")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pattern");
                });

            modelBuilder.Entity("ProjectModels.Sample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<string>("SampleLink")
                        .HasColumnType("text");

                    b.Property<string>("SampleName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sample");
                });

            modelBuilder.Entity("ProjectModels.SamplePlaylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("SampleId")
                        .HasColumnType("integer");

                    b.Property<int>("SampleSetId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SamplePlaylist");
                });

            modelBuilder.Entity("ProjectModels.SampleSets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SampleSet");
                });

            modelBuilder.Entity("ProjectModels.SavedProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("BPM")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SavedProject");
                });

            modelBuilder.Entity("ProjectModels.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("PatternId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("SampleId")
                        .HasColumnType("integer");

                    b.Property<int?>("SavedProjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PatternId");

                    b.HasIndex("SampleId");

                    b.HasIndex("SavedProjectId");

                    b.ToTable("Track");
                });

            modelBuilder.Entity("ProjectModels.UserProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Owner")
                        .HasColumnType("boolean");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("SavedProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SavedProjectId");

                    b.ToTable("UserProject");
                });

            modelBuilder.Entity("ProjectModels.UsersSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean");

                    b.Property<int>("SampleId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UsersSample");
                });

            modelBuilder.Entity("ProjectModels.UsersSampleSets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("SampleSetsId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UsersSampleSets");
                });

            modelBuilder.Entity("ProjectModels.Track", b =>
                {
                    b.HasOne("ProjectModels.Pattern", "Pattern")
                        .WithMany("Tracks")
                        .HasForeignKey("PatternId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("ProjectModels.Sample", "Sample")
                        .WithMany("Track")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("ProjectModels.SavedProject", "SavedProject")
                        .WithMany("Tracks")
                        .HasForeignKey("SavedProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Pattern");

                    b.Navigation("Sample");

                    b.Navigation("SavedProject");
                });

            modelBuilder.Entity("ProjectModels.UserProject", b =>
                {
                    b.HasOne("ProjectModels.SavedProject", "SavedProject")
                        .WithMany("UserProjects")
                        .HasForeignKey("SavedProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("SavedProject");
                });

            modelBuilder.Entity("ProjectModels.Pattern", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("ProjectModels.Sample", b =>
                {
                    b.Navigation("Track");
                });

            modelBuilder.Entity("ProjectModels.SavedProject", b =>
                {
                    b.Navigation("Tracks");

                    b.Navigation("UserProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
